name: C/C++ Release candidate ubuntu22-GTK3-nodeps

on:
  push:
    branches:
      - rc
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04

    env:
      EXEC_NAME: "${{ github.event.repository.name }}"
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'rc'
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: '3.16.x'
    - name: update submodule profiles
      working-directory: ./resources/profiles
      run: git submodule update --init
    - name: change date in version
      run: sed -i "s/+UNKNOWN/_$(date '+%F')/" version.inc
    - name: update clock
      run: sudo hwclock -s
    - name: update apt
      run: sudo apt update
    - name: install gtk3 glew
      run: sudo apt install libgtk-3-dev libglew-dev libudev-dev libdbus-1-dev gettext python3-numpy libopenvdb-dev libfuse2
    - name: install deps
      run: sudo apt install libboost-{system,iostreams,filesystem,thread,log,locale,regex,date-time}-dev libcereal-dev libqhull-dev libglew-dev libopencsg-dev libtbb-dev libblosc-dev libopenexr-dev libopenvdb-dev libgmp-dev libmpfr-dev libcgal-dev libnlopt-dev openssl libcurl4-openssl-dev libwxgtk3.0-gtk3-dev libpng-dev zlib1g-dev libexpat1-dev libocct-ocaf-dev libocct-data-exchange-dev
    - name: build slicer
      run: ./BuildLinux.sh -s
    - name: make .pot
      working-directory: ./build
      run: make gettext_make_pot
    - name: build tar & appimage
      working-directory: ./build
      run: src/BuildLinuxImage.sh -i
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: rc_linux_gtk3.tar
        path: build/${{ github.event.repository.name }}.tar
